fos_ck_editor:
    input_sync: true
    default_config: base_config
    configs:
        base_config:
            toolbar:
                - { name: "styles", items: ['Bold', 'Italic', 'Underline', 'Strike', 'BulletedList', 'Link', 'TextColor', 'JustifyLeft','JustifyCenter','JustifyRight','JustifyBlock', 'Format', 'FontSize'] }